services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  loan-service:
    build:
      context: .
      dockerfile: loan-service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  credit-service:
    build:
      context: .
      dockerfile: credit-service/Dockerfile
    depends_on:
      - rabbitmq

  property-service:
    build:
      context: .
      dockerfile: property-service/Dockerfile
    depends_on:
      - rabbitmq

  decision-service:
    build:
      context: .
      dockerfile: decision-service/Dockerfile
    depends_on:
      - rabbitmq

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    depends_on:
      - rabbitmq

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    command: celery --broker=amqp://guest:guest@rabbitmq:5672// flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  credit-worker:
    build:
      context: .
      dockerfile: credit-service/Dockerfile
    command: celery -A tasks worker --loglevel=info -Q credit_queue
    depends_on:
      - rabbitmq
      - redis

  property-worker:
    build:
      context: .
      dockerfile: property-service/Dockerfile
    command: celery -A tasks worker --loglevel=info -Q property_queue
    depends_on:
      - rabbitmq
      - redis

  decision-worker:
    build:
      context: .
      dockerfile: decision-service/Dockerfile
    command: celery -A tasks worker --loglevel=info -Q decision_queue
    depends_on:
      - rabbitmq
      - redis